### PR TITLE
Use the new Fedora logo

### LINKED ISSUE #1: Adapt for the new Fedora logo
Fedora has a new logo. We need to adapt.

I have some mockups by @mairin in https://twitter.com/mairin/status/1232682105399861248?s=19 but not sure if they have the final logo in them.

### PR DESCRIPTION
**Pull request by hroncok**
Fixes https://github.com/fedora-python/fedora-loves-python/issues/1

@mairin Could you please ack this?

- [x] Design ack: https://pagure.io/design/issue/755
- [x] Fedora Trademark ack: https://pagure.io/Fedora-Council/tickets/issue/362
- [x] Python Software Foundation ack: granted

### CODE REVIEW

**Comment by hroncok** [comment]
One thing I've noticed is that the logo from here: https://pagure.io/fedora-logos/blob/master/f/fedora does not have a TM mark any more. I guess that's intended, right?

EDIT: This was acked by legal. It's OK to leave the TM mark off.

**Review by mairin — COMMENTED** [review]
The monochrome & color versions look fine. The preview svg / png have the grey outline and the dropshadow though, I wouldn't have applied the shadow exactly that way. What is the intended use of the preview, to display in a github readme or elsewhere?

**Comment by hroncok** [comment]
> The preview svg / png have the grey outline and the dropshadow though, I wouldn't have applied the shadow exactly that way.

Note that this was not introduced with this change. Only the Fedora logo was changed, the color of the :heart:, and the monochrome version was added.

> What is the intended use of the preview, to display in a github readme or elsewhere?

Pretty much the README. Very occasionally I use it when the background is light, but whenever possible, we use a contrast background to make the white border visible.

**Comment by mairin** [comment]
I can give you a version that has the drop shadow adjusted if you don't mind.
I am going to research the TM thing because I was advised not to use it, but that wasn't for the specific circumstance where the mark is next to another trademarked mark.
One question too... so when I mocked up the new Fedora :heart: Python logo, I added a version that has a very slight gradient. Do you have a preference (or would you like both?)

Gradient (vote :rocket:)
Screenshot from 2021-04-14 10-22-53

No gradient (vote :tada:)
Screenshot from 2021-04-14 10-24-18

(EDIT: There are more proposals below this comment.)

**Comment by hroncok** [comment]
I don't have a (strong) preference. I'd prefer no-gradient, but it doesn't play that nicely with the Python logo.

What if we de-gradient'ed the Python logo as well (should be fine because changing the colors of the Python logo is not generally frowned upon: *modifications that leave the shape -- but not necessarily the colors -- unaltered are likely to be approved*):



WDYT?

**Comment by hroncok** [comment]
Others, if you are reading this and have a preference, please indicate it by adding :rocket: or :tada: to @mairin's comment or :+1: to my comment. Feel free to add more if you like 2 options more than a third or if you like all of them.

**Comment by mairin** [comment]
I am waiting for Legal to clarify whether or not the TM is needed in a two-trademark design. 

I like the superflat python one but I'd make the blue closer to the original main blue of the Python logo rather than matchy-match the Fedora blue, if that makes sense. I can update the assets and provide here once I hear back from legal. I'll put it on my calendar now to follow up on Friday if I don't hear back.

**Comment by hroncok** [comment]
Like this?

preview

**Comment by hroncok** [comment]
I've shared this on python-devel.
I plan to update the PR for the most favorable next week.

**Review by mairin — CHANGES_REQUESTED** [review]
Hey Miro, it looks like GitHub blocks SVG so I just sent updated SVGs & a preview PNG with flat python logo colors, removed TM for Fedora, and adjusted the drop shadow on the previews to follow what we typically use in Fedora these days. With those updates I can give you design team approval. (Oh and of course can be updated if gradient gets the vote, etc)

**Comment by hroncok** [comment]
I've received them. Will update this PR shortly

**Comment by hroncok** [comment]
Thanks. I've committed your changes here.

**Comment by hroncok** [comment]
I've pushed a commit that moves the logo back to the original dimension/position. Is that OK?

**Comment by hroncok** [comment]
I think the movement was just a pre-existing difference between the real thing and a preview. My bad.

**Comment by mairin** [comment]
It should be exactly the same, I didn't move anything.

**Comment by hroncok** [comment]
> It should be exactly the same, I didn't move anything.

Yeah, it was my PEBKAC, sorry about that.

**Comment by hroncok** [comment]
@mairin Could you please give final ack fro what is in this PR (better ignore the issue comments and look at the files added/changed)?

**Review by mairin — CHANGES_REQUESTED** [review]
The monochrome and main SVG look fine. The preview images still have the old dropshadow & outline. Can those be updated?

**Comment by hroncok** [comment]
I am pretty sure they don't, may this be a browser cache thing?

**Comment by mairin** [comment]
Ugh how annoying, let me shift reload, sorry about that!

**Review by mairin — APPROVED** [review]
Perfecto, shipit +1

**Comment by hroncok** [comment]
Thanks @mairin.

I've asked PSF to approve this.

**Comment by hroncok** [comment]
> Hi Miro,
> 
> the logos look fine and a compliant with our policy, so we can
> grant authorization.
> 
> Thanks,
> Marc-Andre Lemburg
> Python Software Foundation

**Comment by hroncok** [comment]
Thanks everybody for participating!

**Pull request merged**
